### ISSUE TITLE
Frame / Photo margin ?

### ISSUE THREAD

**Issue by rhaamo** [codec-xyz/photo_frame_manager#2]
Hi,

I've tried to make a custom frame, basic one with the front face as the full picture, but it looks like I have some margin I can't remove/change:
![Unity_LUZy5RPh6m](https://github.com/codec-xyz/photo_frame_manager/assets/8625/5d9b1eab-0964-4fa2-98a5-a265c0a2a7ba)

The scale is like that on the generated frame:
![image](https://github.com/codec-xyz/photo_frame_manager/assets/8625/ea4de1ba-5121-4947-a9bc-e41395b22c6c)

If I happens to change from `100.6667` to `66.67`:
![image](https://github.com/codec-xyz/photo_frame_manager/assets/8625/bc0033d8-9d07-4e82-987a-1aac8b293b03)

The frame is now the same size as the picture:
![image](https://github.com/codec-xyz/photo_frame_manager/assets/8625/04e6140e-074f-44a0-809a-51b02baa4992)

Is it a builtin margin ? Or maybe I haven't managed to find the setting for that.
Some of my settings:

![image](https://github.com/codec-xyz/photo_frame_manager/assets/8625/5c8107c3-e62a-45ef-a724-9677537a6e17)
![image](https://github.com/codec-xyz/photo_frame_manager/assets/8625/a497cee8-04eb-4ba9-881f-b2145bff41bc)
![image](https://github.com/codec-xyz/photo_frame_manager/assets/8625/108d40fd-fed5-4a49-af0b-a6cbe5a8859c)

**Comment by codec-xyz** [comment]
It seems most likely that the issue here is your picture frame is the wrong size.

`PhotoFrameType > PhotoDimensions` tells the photo frame manager how big the photo should be to fit into the picture frame. You have it set to `"Larger Side Is One"`. This means the larger side of the photo should be one unit length to fit the photo frame. (Note the scale of the photo frame in the scene is completely separate. It is done afterwards to both the photo and the frame and does not effect this setting.)

Most likely your picture frame model is simply the wrong size. From the scale values in the screen shots the slot for the photo looks to be 1.509925 x 1.509925 units. From the settings the photo frame manager assume slot for the photo to be 1 x 1 units. Assuming this is the problem here a few different ways to fix the issue (you only need to do one)...
- Simplest: Set the FBX scale factor to 0.66228455 for unity to scale the model to the correct size while importing. (0.66228455 = 1 / 1.509925)
- **or** Edit the picture frame in another program making the slot for the photo be 1 x 1 units and reexport the FBX.
- **or** Set `PhotoFrameType > PhotoDimensions` to `"Use Aspect Ratio"`. This setting lets you tell the photo frame manager the exact dimensions for the photo slot. Set `PhotoFrameType > photo frame model list > Aspect Ratio` to (x: 1.509925, y: 1.509925).

**Comment by codec-xyz** [comment]
Do let me know if this answer solves your problem. Additionally the section on [Photo Frame Type Files](https://github.com/codec-xyz/photo_frame_manager?tab=readme-ov-file#photo-frame-type-files) has been expanded with more detail.

**Comment by rhaamo** [comment]
I did go the easy route by changing the FBX scale factor, I might have done a whoopsie when exporting the FBX, I will redo it later, thanks !
